Refactoring
ferbiy/Registration pull request #1
Opened 2020-11-03 13:31 UTC by ferbiy

new services for sending request and validation; try to use BEM in index.css; changed name of module "bankblock" to "bank-block"; create new components: bank-accounts, add-account, personal-info, credentials. Most of the code has been rewritten to improve readability

2020-11-03 19:46 UTC, shurka2plus commented on src/styles/index.css
> +.h2 {
Does not look like BEM approach. Options:
```
.heading {}
.heading--large {}
.heading--small {}

2020-11-03 19:49 UTC, shurka2plus commented on src/styles/index.css
> +.field-block {
Proposal for better name - maybe form-field?

2020-11-03 19:59 UTC, shurka2plus commented on src/styles/index.css
> +.select {
BEM its not just using classes instead of HTML elements. You should consider element like reusable block with some mission. 
For example here you can define basic styling for dropdown in root class and add some modifier to customize its look with "background: url("../img/arrow-down."

2020-11-03 20:06 UTC, shurka2plus commented on src/styles/index.css
>  body {
Just for your knowledge, with scss you can use nesting for classes. 
Found project with BEM example for raw css and scss for comparison
raw css
https://github.com/khaledayed/BEM-CSS-Example/blob/master/css/style.css
scss
https://github.com/khaledayed/BEM-CSS-Example/blob/master/sass/style.scss

Warning: as I remember nesing level should not be more then 3-4

2020-11-03 20:07 UTC, shurka2plus commented on src/components/add-account.js
> +          className="button button--big"
good example of using BEM :)

2020-11-03 20:22 UTC, shurka2plus commented on src/components/App.js
> +  handleCredentials(e) {
Naming should be more precise handleCredentialsChange/handleCredentialsUpdate
Check below methods as well

2020-11-03 20:46 UTC, shurka2plus commented on src/components/App.js
>    }
Still we have this low level stuff here:
```
 const { id, value } = e.target;
```
It should be encapsulated in the PersonalInfo component. 


You have several options here - create state in PersonalInfo and pass aggregated object here like you did for bankBlock. Also you can create own handler in PersonalInfo without managing state like this (code is not tested, so correct it):
```
class PersonalInfo {
...
handleFieldChange(e) { // this handler can be used for all fields
    const { id, value } = e.target;
    const updatedInfo = {};
    updatedInfo[id] = value;
    this.props.handlePersonalInfoChange(updatedInfo);
  }
...
}
```
```
class App {
...
handlePersonalInfoChange(updatedInfo) {
   const currentInfo = this.state.personalInfo;
   const newInfo = { ...currentInfo, ...updatedInfo }; // with spread operator merging old and updated fields here
   this.setState({ personalInfo: newInfo });
}
```

2020-11-03 20:48 UTC, shurka2plus commented on src/components/App.js
>      if (validation(this.state)) {
To improve readability:
```
   if (isValid(this.state)) {

2020-11-03 20:53 UTC, shurka2plus requested changes
See comments

2020-11-05 09:01 UTC, ferbiy commented on src/styles/index.css
> +.h2 {
Fixed.

2020-11-05 09:01 UTC, ferbiy commented on src/styles/index.css
> +.field-block {
Fixed.

2020-11-05 09:02 UTC, ferbiy commented on src/styles/index.css
> +.select {
Tried to fix. Check if I understood correctly.

2020-11-05 09:03 UTC, ferbiy commented on src/components/add-account.js
> +          className="button button--big"
ok :)

2020-11-05 09:03 UTC, ferbiy commented on src/components/App.js
> +  handleCredentials(e) {
Changed.

2020-11-05 09:03 UTC, ferbiy commented on src/components/App.js
>    }
Ok, changed for PersonalInfo and Credentials

2020-11-05 09:04 UTC, ferbiy commented on src/components/App.js
>      if (validation(this.state)) {
Fixed (just forgot).

2020-11-05 20:53 UTC, shurka2plus commented on src/styles/index.css
> +.select {
yep, looks ok

2020-11-05 20:58 UTC, shurka2plus approved these changes

2020-11-05 20:59 UTC, shurka2plus commented
PR reviewed, comments fixed and its Approved.
Further step - press Merge pull request and it will be closed to master

2020-11-06 06:23 UTC, merged